E_shop/E_shop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.HOME, name='home'),
                  path('base/', views.BASE, name='base'),
                  path('products/', views.PRODUCT, name='products'),
                  path('about_us/', views.ABOUT_US, name='about_us'),
                  path('blogs/', views.BLOGS, name='blogs'),
                  path('products/<str:id>', views.PRODUCT_DETAILS_PAGE, name='product_details'),
                  path('search/', views.SEARCH, name='search'),
                  path('contact/', views.Contact_Page, name='contact'),
                  path('register/', views.HandleRegister, name='register'),
                  path('login/', views.HandleLogin, name='login'),
                  path('logout/', views.HandleLogout, name='logout'),

                  # ---cart------
                  path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
                  path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
                  path('cart/item_increment/<int:id>/',
                       views.item_increment, name='item_increment'),
                  path('cart/item_decrement/<int:id>/',
                       views.item_decrement, name='item_decrement'),
                  path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
                  path('cart/cart-detail/', views.cart_detail, name='cart_detail'),
                  path('cart/checkout/', views.Check_out, name='checkout'),
                  path('cart/checkout/placeorder', views.PLACE_ORDER, name='place_order'),
                  path('success', views.SUCCESS, name='success'),
                  path('Your_Order', views.Your_Order, name='your_order'),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_shop/store_app/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.

class Categories(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Filter_Price(models.Model):
    FILTER_PRICE = (
        ('100 TO 1000','100 TO 1000'),
        ('1000 TO 10000','1000 TO 10000'),
        ('10000 TO 20000','10000 TO 20000'),
        ('20000 TO 30000','20000 TO 30000'),
        ('30000 TO 40000','30000 TO 40000'),
        ('40000 TO 50000','40000 TO 50000'),
        ('50000 TO 60000','50000 TO 60000'),
    )

    price = models.CharField(choices=FILTER_PRICE,max_length=60)

    def __str__(self):
        return self.price

class Product(models.Model):
    CONDITION = (('New','New'),('Old','Old'))
    STOCK = (('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock'))
    STATUS = (('Publish', 'Publish'), ('Draft', 'Draft'))

    unique_id = models.CharField(unique=True,max_length=200,null=True,blank=True)
    image = models.ImageField(upload_to='Product_image/img')
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    condition = models.CharField(choices=CONDITION,max_length=100)
    information = RichTextField(null=True)
    description = RichTextField(null=True)
    stock = models.CharField(choices=STOCK,max_length=200)
    status = models.CharField(choices=STATUS, max_length=200)
    created_date = models.DateTimeField(default=timezone.now)

    categories = models.ForeignKey(Categories,on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE)
    color = models.ForeignKey(Color,on_delete=models.CASCADE)
    filter_price = models.ForeignKey(Filter_Price,on_delete=models.CASCADE)


    def save(self, *args,**kwargs):
        if self.unique_id is None and self.created_date and self.id:
            self.unique_id = self.created_date.strftime('75%Y%m%d23') + str(self.id)
        return super().save(*args,**kwargs)

    def __str__(self):
        return self.name

class Images(models.Model):
    image = models.ImageField(upload_to='Product_image/img')
    product = models.ForeignKey(Product,on_delete=models.CASCADE)

class Tag(models.Model):
    name = models.CharField(max_length=200)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)

class Contact_us(models.Model):
    name = models.CharField(max_length=2000)
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=300)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    address = models.TextField()
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postcode = models.IntegerField()
    phone = models.IntegerField()
    email = models.EmailField(max_length=200)

    amount = models.CharField(max_length=100)
    payment_id = models.CharField(max_length=300,null=True,blank=True)
    paid = models.BooleanField(default=False,null=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=100)
    image = models.ImageField(upload_to="Product_Images/Order_Img")
    quantity = models.CharField(max_length=20)
    price = models.CharField(max_length=50)
    total = models.CharField(max_length=1000)

    def __str__(self):
        return self.order.user.username

E_shop/templates/Main/about_us.html
{% extends 'Main/base.html' %}
{% block content %}
{% load static %}
<!-- About section Start -->
        <div class="about-area pt-100px">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="about-wrapper text-center">
                            <div class="about-contant">
                                <h2 class="title">
                                    <span>Smart Fashion </span>
                                    With Smart Devices
                                </h2>
                                <p>Hmart technology drives path-breaking, customer-focused innovation that makes high quality products accessible to Indian shoppers, besides making the online shopping experience convenient, intuitive and seamless.</p>
                            </div>
                            <div class="promo-video">
                                <img src="{% static 'assets/images/about/promo-video-img.webp' %}" alt="">
                                <a href="https://www.youtube.com/watch?v=J0Aq44Pze-w&ab_channel=OracleDevelopers" class="venobox overlay-box" data-vbtype="video"><span
                                    class="fa fa-play"><i class="ripple"></i></span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- About section End -->
<!-- Team Area Start -->
        <div class="team-area">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title text-center">
                            <h2 class="title line-height-1">Team Member</h2>
                            <p></p>
                        </div>
                    </div>
                </div>
                <div class="row mb-n-30px" >
                    <div class="col-xl-4 col-lg-4 col-sm-6 col-md-6 mb-lm-30px ">
                        <!-- Single Team -->
                        <div class="team-wrapper">
                            <div class="team-image overflow-hidden">
                                <img src="{% static 'assets/images/team/4.webp' %}" alt="">
                                <ul class="team-social d-flex">

                                    <li>
                                        <a title="Twitter" target="_blank" rel="noopener noreferrer" href="https://twitter.com/Dushyant5656"><i class="fa fa-twitter" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a title="LinkedIn" target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/dushyant-gautam-890bb420b/"><i class="fa fa-linkedin" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a title="Github" target="_blank" rel="noopener noreferrer" href="https://github.com/DUSHYANT2727"><i class="fa fa-github" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="team-inner">
                                <div class="team-content">
                                    <h6 class="title">Dushyant Gautam</h6>
                                    <span class="sub-title">Team Member</span>
                                </div>
                            </div>
                        </div>
                        <!-- Single Team -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Team Area End -->
<!-- Feature Area Srart -->
        <div class="feature-area pt-100px pb-100px">
            <div class="container">
                <div class="feature-wrapper">
                    <div class="single-feture-col mb-md-30px mb-lm-30px">
                        <!-- single item -->
                        <div class="single-feature">
                            <div class="feature-icon">
                                <img src="{% static 'assets/images/icons/1.png' %}" alt="">
                            </div>
                            <div class="feature-content">
                                <h4 class="title">Free Shipping</h4>
                                <span class="sub-title">Capped at ₹ 39 per order</span>
                            </div>
                        </div>
                    </div>
                    <!-- single item -->
                    <div class="single-feture-col mb-md-30px mb-lm-30px">
                        <div class="single-feature">
                            <div class="feature-icon">
                                <img src="{% static 'assets/images/icons/2.png' %}" alt="">
                            </div>
                            <div class="feature-content">
                                <h4 class="title">Card Payments</h4>
                                <span class="sub-title">12 Months Installments</span>
                            </div>
                        </div>
                    </div>
                    <!-- single item -->
                    <div class="single-feture-col">
                        <div class="single-feature">
                            <div class="feature-icon">
                                <img src="{% static 'assets/images/icons/3.png' %}" alt="">
                            </div>
                            <div class="feature-content">
                                <h4 class="title">Easy Returns</h4>
                                <span class="sub-title">Shop With Confidence</span>
                            </div>
                        </div>
                        <!-- single item -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Feature Area End -->

{% endblock %}

E_shop/templates/Main/blogs.html
{% extends 'Main/base.html' %}
{% block content %}
{% load static %}
<!-- Blog Area Start -->
        <div class="blog-grid pb-100px pt-100px main-blog-page single-blog-page">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12 offset-lg-2">
                        <div class="blog-posts">
                            <div class="single-blog-post blog-grid-post">
                                <div class="blog-image single-blog">
                                    <img class="img-fluid h-auto border-radius-10px" src="{% static 'assets/images/blog-image/single-blog.webp' %}" alt="blog" />
                                </div>
                                <div class="blog-post-content-inner mt-30px">
                                    <div class="blog-athor-date">
                                        <span class="blog-date"><i class="fa fa-calendar" aria-hidden="true"></i> 27,Jun 2024</span>
                                        <span><a class="blog-author" href="https://telecom.economictimes.indiatimes.com/tag/electronics"><i class="fa fa-user" aria-hidden="true"></i>Updates</a></span>
                                    </div>
                                    <h4 class="blog-title"> Principles of Psychology You Can Use to Improve Your Smart Product </h4>
                                    <p data-aos="fade-up">
                                        Design is most effective when executed with knowledge of psychology. Knowing how people react to visual stimuli allows the crafting of an effective design, without psychology, you are guessing. Psychology is a vastly fluctuating and massive subject, but that doesn’t mean you need a Ph.D. to use it in your design. There are simple psychological principles you can use to improve the effectiveness of your design even without knowing the theory behind it.

While there are hundreds of relevant principles, the following ten can be used to improve your designs’ aesthetic quality, usability, and comprehension.
                                    </p>
                                    <div class="quate-speech-area">
                                        <p class="quate-speech" data-aos="fade-up" data-aos-delay="200">
                                            Things don't have to change the world to be important. Technology is nothing. What's important is that you have a faith in people, that they're basically good and smart, and if you give them tools, they'll do wonderful things with them. I've always been attracted to the more revolutionary changes.
                                        </p>
                                        <span class="quater">Steve Jobs</span>
                                    </div>
                                </div>
                                <div class="single-post-content">
                                    <p data-aos="fade-up" data-aos-delay="200">
                                        You may consider yourself self-aware and in complete control… well I’ve got news for you, you’re not. For centuries cognition has tricked humans into believing their actions are entirely thought-out and preplanned. Modern psychology says otherwise. Much of human behavior is still rooted and influenced by our “old brain,” the part of our mind controlling the survival instincts that kept our ancestors alive (Weinschenk, Nuero Web Design, 2009.) The old brain reacts much faster than conscious thought and is triggered anytime we’re exposed to a representation of food, shelter, danger or reproduction. These are called “visceral reactions” as they originate from the central nervous system (Norman, Emotional Design, 2005.)
                                    </p>
                                </div>
                            </div>
                            <div class="another-post">
                                <div class="content-side">
                                    <p class="mb-30px">Related to visceral reactions is the cost-benefit principle which surmises behavior is regulated by the perceived difficulty of a task concerning the perceived reward (The Journal of Neuroscience, 8 April 2009, 29(14): 4531-4541.) Basic human behavior can be summed up as opportunity seeking and threat avoidance. For example, your body is hardwired to seek energy-dense food, which is why calorie-dense foods like french fries and chocolate are more challenging to resist than lettuce. Because the fuel for energy (food) used to be scarce and took energy to obtain, we have developed an uncanny drive to conserve energy where possible. Our ancestors survived by limiting their energy usage to activities that would provide high benefits.</p>
                                    </div>
                                <div class="image-side">
                                    <img src="{% static 'assets/images/blog-image/side-image.webp' %}" alt="">
                                </div>
                            </div>
                            <p>It only takes a little exploration into cognitive psychology to smash the illusion that we have a firm grasp of the world around us. It seems our brain loves to take shortcuts and make assumptions while reassuring ourselves that everything has been well thought out. The most nefarious of examples are the Gestalt Principles. Developed by german psychologists in the 1920s, the principles describe how our brain assumes unification or relatedness to visuals based on proximity and whitespace. For example, visuals in close proximity are perceived as related when not necessarily the case. Another example is similarity, where elements that look similar are considered related and elements that look different are unrelated  (Humphrey, G. (1924). The psychology of the gestalt. Journal of Educational Psychology.)</p>
                            <!-- single blog post -->
                            </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- Blag Area End -->

{% endblock %}

E_shop/templates/Main/contact.html
{% extends 'Main/base.html' %}
{% block content %}


<!-- Contact Area Start -->
        <div class="contact-area">
            <div class="container">
                <div class="contact-wrapper">
                    <div class="row">
                        <div class="col-12">
                            <div class="contact-form">
                                <div class="contact-title mb-30">
                                    <h2 class="title">Send A Quest</h2>
                                </div>
                                <form class="contact-form-style"  action="/contact/" method="post">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <input name="name" placeholder="Name*" type="text" />
                                        </div>
                                        <div class="col-lg-6">
                                            <input name="email" placeholder="Email*" type="email" />
                                        </div>
                                        <div class="col-lg-12">
                                            <input name="subject" placeholder="Subject*" type="text" />
                                        </div>
                                        <div class="col-lg-12 text-center">
                                            <textarea name="message" placeholder="Your Message*"></textarea>
                                            <button class="btn btn-primary" type="submit">Send Message</button>
                                        </div>
                                    </div>
                                </form>
                                <p class="form-messege"></p>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="contact-info">
                                <div class="single-contact">
                                    <div class="icon-box">
                                        <img src="assets/images/icons/contact-1.png" alt="">
                                    </div>
                                    <div class="info-box">
                                        <h5 class="title">Address</h5>
                                        <p>PALWAL<br>
                                        HARYANA</p>
                                    </div>
                                </div>
                                <div class="single-contact">
                                    <div class="icon-box">
                                        <img src="assets/images/icons/contact-2.png" alt="">
                                    </div>
                                    <div class="info-box">
                                        <h5 class="title">Phone No</h5>
                                        <p><a href="tel:0123456789">9996927279</a></p>
                                        <p><a href="tel:0123456789">9255527765</a></p>
                                    </div>
                                </div>
                                <div class="single-contact m-0">
                                    <div class="icon-box">
                                        <img src="assets/images/icons/contact-3.png" alt="">
                                    </div>
                                    <div class="info-box">
                                        <h5 class="title">Email/Web</h5>
                                        <p><a href="mailto:g60509456@gmail.com">g60509456@gmail.com</a></p>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Contact Area End -->
        <!-- map Area Start -->
        <div class="contact-map">
            <div id="mapid">
                <div class="mapouter">
                    <div class="gmap_canvas">
                        <iframe src="https://maps.google.com/maps?q=4847+6G6,%20Chirawata,%20Haryana%20121102&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed" ></iframe>
                        <a href="https://www.eireportingonline.com">ei reporting</a>
                        </div>
                    </div>
            </div>
        </div>
        <!-- map Area End -->

{% endblock %}

E_shop/templates/Main/product_single.html
{% extends 'Main/base.html' %}
{% block content %}

<!-- Product Details Area Start -->
        <div class="product-details-area pt-100px pb-100px">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-sm-12 col-xs-12 mb-lm-30px mb-md-30px mb-sm-30px">
                        <!-- Swiper -->
                        <div class="swiper-container zoom-top">
                            <div class="swiper-wrapper">
                                {% for i in prod.images_set.all %}
                                <div class="swiper-slide">
                                    <img class="img-responsive m-auto" src="/{{i.image}}" alt="">
                                    <a class="venobox full-preview" data-gall="myGallery" href="/{{i.image}}">
                                        <i class="fa fa-arrows-alt" aria-hidden="true"></i>
                                    </a>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="swiper-container mt-20px zoom-thumbs slider-nav-style-1 small-nav">
                            <div class="swiper-wrapper">
                                {% for i in prod.images_set.all %}
                                <div class="swiper-slide">
                                    <img class="img-responsive m-auto" src="/{{i.image}}" alt="">
                                </div>
                                {% endfor %}
                            </div>
                            <!-- Add Arrows -->
                            <div class="swiper-buttons">
                                <div class="swiper-button-next"></div>
                                <div class="swiper-button-prev"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-12 col-xs-12" data-aos="fade-up" data-aos-delay="200">
                        <div class="product-details-content quickview-content ml-25px">
                            <h2>{{prod.name | truncatewords:8}}</h2>
                            <div class="pricing-meta">
                                <ul class="d-flex">
                                    <li class="new-price">₹{{prod.price}}</li>
                                </ul>
                            </div>
                            <div class="pro-details-rating-wrap">
                                <div class="rating-product">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </div>
                                <span class="read-review"><a class="reviews" href="#">(5 Customer Review)</a></span>
                            </div>
                            <p class="mt-30px">{{prod.description | truncatewords:35 | safe}}</p>
                            <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                                <span>SKU:</span>
                                <ul class="d-flex">
                                    <li>
                                        <a href="#">Ch-256xl</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                                <span>Categories: </span>
                                <ul class="d-flex">
                                    <li>
                                        <a href="#">{{prod.categories}}, </a>
                                    </li>

                                </ul>
                            </div>
                            <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                                <span>Tags: </span>
                                <ul class="d-flex">
                                    <li>
                                        {% for i in prod.tag_set.all %}
                                        <a href="#">{{i.name}}, </a>
                                        {% endfor %}
                                    </li>

                                </ul>
                            </div>
                            <div class="pro-details-quality">
                                <div class="cart-plus-minus">
                                    <input class="cart-plus-minus-box" type="text" name="qtybutton" value="1" />
                                </div>
                                <div class="pro-details-cart">
                                    <button class="add-cart"> Add To Cart</button>
                                </div>
                                <div class="pro-details-compare-wishlist pro-details-wishlist ">
                                    <a href="wishlist.html"><i class="pe-7s-like"></i></a>
                                </div>
                                <div class="pro-details-compare-wishlist pro-details-wishlist ">
                                    <a href="compare.html"><i class="pe-7s-refresh-2"></i></a>
                                </div>
                            </div>
                        </div>
                        <!-- product details description area start -->
                        <div class="description-review-wrapper">
                            <div class="description-review-topbar nav">
                                <button data-bs-toggle="tab" data-bs-target="#des-details2">Information</button>
                                <button class="active" data-bs-toggle="tab" data-bs-target="#des-details1">Description</button>

                            </div>
                            <div class="tab-content description-review-bottom">
                                <div id="des-details2" class="tab-pane">
                                    <div class="product-anotherinfo-wrapper text-start">
                                        <ul>
                                            <li>{{prod.information | safe}}</li>

                                        </ul>
                                    </div>
                                </div>
                                <div id="des-details1" class="tab-pane active">
                                    <div class="product-description-wrapper">
                                        <p>
                                            {{prod.description | safe}}
                                        </p>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <!-- product details description area end -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Product Area Start -->

{% endblock %}